version: '3.8'

services:
  db:
    image: mysql:8
    container_name: autoparts_mysql
    restart: always
    environment:
      MYSQL_DATABASE: Autoparts
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    container_name: autoparts_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: Autoparts
      DB_USER: root
      DB_PASSWORD: rootpass
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  db-data:
